import {
  faParking,
  faUtensils,
  faWifi,
  faToilet,
  faSnowflake,
  faShieldAlt,
  faTruck,
  faCouch,
  faChargingStation,
  faUsers,
  faBoxes,
  faFireExtinguisher,
  faFan,
  faLightbulb,
  faHospital,
  faHotel,
  faBowlFood,
  faBank,
  faMoneyBill,
  faTrain,
  faRestroom,
  faBell,
  faBuilding,
  faCamera,
  faCar,
  faCartPlus,
  faClock,
  faCode,
  faCoffee,
  faComment,
  faCompass,
  faCrown,
  faDesktop,
  faDog,
  faDoorOpen,
  faDumbbell,
  faEnvelope,
  faEye,
  faFeather,
  faFilm,
  faFlask,
  faGamepad,
  faGift,
  faGlobe,
  faGuitar,
  faHammer,
  faHeart,
  faHelicopter,
  faIceCream,
  faIdCard,
  faKey,
  faLeaf,
  faLemon,
  faLock,
  faMap,
  faMicrophone,
  faMobile,
  faMoon,
  faMotorcycle,
  faMugHot,
  faPaintBrush,
  faPaperPlane,
  faPaw,
  faPhone,
  faPlane,
  faPlug,
  faPrint,
  faRoad,
  faRobot,
  faRocket,
  faSchool,
  faServer,
  faShip,
  faShoppingBag,
  faShoppingBasket,
  faShoppingCart,
  faShower,
  faSkating,
  faSkiing,
  faSnowman,
  faSpa,
  faStar,
  faStethoscope,
  faSubway,
  faSuitcase,
  faSun,
  faSyringe,
  faTablet,
  faTaxi,
  faTools,
  faTooth,
  faTree,
  faTv,
  faUniversity,
  faUserShield,
  faUtensilSpoon,
  faVideo,
  faVolleyball,
  faWallet,
  faWater,
  faWind,
  faWineBottle,
  faWrench,
} from "@fortawesome/free-solid-svg-icons";

const iconMap: Record<string, any> = {
  wifi: faWifi,
  parking: faParking,
  food: faUtensils,
  restroom: faToilet,
  ac: faSnowflake,
  security: faShieldAlt,
  loading: faTruck,
  lounge: faCouch,
  charging: faChargingStation,
  meeting_room: faUsers,
  storage: faBoxes,
  fire_safety: faFireExtinguisher,
  ventilation: faFan,
  power_backup: faLightbulb,
  hospital: faHospital,
  restaurant: faHotel,
  cafe: faBowlFood,
  bank: faBank,
  atm: faMoneyBill,
  supermarket: faRestroom,
  metro: faTrain,

  alert: faBell,
  building: faBuilding,
  camera: faCamera,
  car: faCar,
  cart: faCartPlus,
  clock: faClock,
  code: faCode,
  coffee: faCoffee,
  comment: faComment,
  compass: faCompass,
  crown: faCrown,
  desktop: faDesktop,
  dog: faDog,
  entrance: faDoorOpen,
  gym: faDumbbell,
  email: faEnvelope,
  view: faEye,
  feather: faFeather,
  movie: faFilm,
  lab: faFlask,
  gaming: faGamepad,
  gift: faGift,
  world: faGlobe,
  music: faGuitar,
  repair: faHammer,
  love: faHeart,
  chopper: faHelicopter,
  dessert: faIceCream,
  id: faIdCard,
  key: faKey,
  eco: faLeaf,
  lemon: faLemon,
  lock: faLock,
  map: faMap,
  mic: faMicrophone,
  mobile: faMobile,
  night: faMoon,
  bike: faMotorcycle,
  tea: faMugHot,
  art: faPaintBrush,
  send: faPaperPlane,
  pet: faPaw,
  call: faPhone,
  flight: faPlane,
  plug: faPlug,
  print: faPrint,
  road: faRoad,
  ai: faRobot,
  rocket: faRocket,
  school: faSchool,
  server: faServer,
  ship: faShip,
  bag: faShoppingBag,
  basket: faShoppingBasket,
  cart2: faShoppingCart,
  bath: faShower,
  skating: faSkating,
  skiing: faSkiing,
  snowman: faSnowman,
  spa: faSpa,
  favorite: faStar,
  medical: faStethoscope,
  subway: faSubway,
  luggage: faSuitcase,
  sunlight: faSun,
  injection: faSyringe,
  tablet: faTablet,
  taxi: faTaxi,
  tools: faTools,
  dentist: faTooth,
  tree: faTree,
  tv: faTv,
  college: faUniversity,
  guard: faUserShield,
  spoon: faUtensilSpoon,
  video: faVideo,
  volleyball: faVolleyball,
  wallet: faWallet,
  water: faWater,
  wind: faWind,
  wine: faWineBottle,
  wrench: faWrench,
};

export default iconMap;
